import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    extend: {
      colors: {
        background: '#f0f4f8',
        'on-secondary-container': '#5c647a',
        'on-secondary': '#ffffff',
        'primary-fixed-dim': '#ffb59f',
        'surface-dim': '#cbdbf5',
        'secondary-container': '#dae2fd',
        error: '#ba1a1a',
        'tertiary-fixed': '#c9e6ff',
        'on-secondary-fixed': '#131b2e',
        'outline-variant': '#e2bfb5',
        'on-tertiary-fixed': '#001e2f',
        'on-error': '#ffffff',
        'surface-tint': '#ae3100',
        'inverse-primary': '#ffb59f',
        'surface-container': '#e5eeff',
        outline: '#8e7068',
        'on-primary-fixed': '#3a0a00',
        'on-primary': '#ffffff',
        'surface-container-low': '#eff4ff',
        'on-tertiary-container': '#fcfcff',
        'on-tertiary-fixed-variant': '#004c6e',
        'on-primary-fixed-variant': '#852400',
        'on-surface-variant': '#5a4139',
        'on-primary-container': '#fffbff',
        'primary-container': '#d04411',
        'primary-fixed': '#ffdbd0',
        primary: '#aa3000',
        'on-error-container': '#93000a',
        'surface-container-highest': '#d3e4fe',
        'surface-bright': '#f0f4f8',
        'secondary-fixed-dim': '#bec6e0',
        'inverse-surface': '#213145',
        'tertiary-fixed-dim': '#89ceff',
        'error-container': '#ffdad6',
        'surface-variant': '#d3e4fe',
        secondary: '#565e74',
        'inverse-on-surface': '#eaf1ff',
        'on-tertiary': '#ffffff',
        'secondary-fixed': '#dae2fd',
        'surface-container-high': '#dce9ff',
        'on-surface': '#0b1c30',
        surface: '#f0f4f8',
        'surface-container-lowest': '#ffffff',
        tertiary: '#00628d',
        'on-background': '#0b1c30',
        'tertiary-container': '#007cb1',
        'on-secondary-fixed-variant': '#3f465c',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        gutter: '24px',
        lg: '40px',
        sm: '16px',
        md: '24px',
        xl: '64px',
        xs: '8px',
        base: '4px',
        'margin-mobile': '16px',
        'margin-desktop': '32px',
      },
      fontFamily: {
        'body-lg': ['Inter'],
        'body-sm': ['Inter'],
        'headline-lg': ['Inter'],
        'display-lg': ['Inter'],
        'headline-lg-mobile': ['Inter'],
        'title-md': ['Inter'],
        'label-caps': ['JetBrains Mono'],
      },
      fontSize: {
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'title-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
};

export default config;
