import type { StitchPageConfig } from '@/components/command-center/StitchPage';

export const stitchPages: Record<string, StitchPageConfig> = {
  'nexus-operational-intelligence': {
    layout: 'command',
    eyebrow: 'NEXUS',
    title: 'Operational Intelligence',
    description: 'A cross-company intelligence layer for performance, approvals, people, revenue, and risk signals.',
    icon: 'hub',
    aiPrompt: 'Ask for bottlenecks, attendance risk, client exposure, or next actions across the EMS.',
    aiSummary: 'Nexus combines dashboard, AI overview, management review, and follow-up data to surface the operational story behind the numbers.',
    endpoints: ['/dashboard/stats', '/ai-overview/owner-dashboard', '/management-review/weekly', '/follow-up-tasks'],
    metrics: [
      { label: 'Health Score', value: '92%', meta: 'Stable', tone: 'tertiary', icon: 'monitoring' },
      { label: 'Open Tasks', value: '18', meta: 'AI ranked', tone: 'primary', icon: 'task_alt' },
      { label: 'Risk Signals', value: '4', meta: 'Needs review', tone: 'error', icon: 'warning' },
      { label: 'Live Modules', value: '15', meta: 'Mapped', icon: 'apps' },
    ],
    primaryItems: [
      { title: 'Executive queue needs attention', subtitle: 'Leaves, expenses, and documents waiting for approval', status: 'Review' },
      { title: 'Client renewal pulse', subtitle: 'Upcoming contract and invoice signals are being monitored', status: 'Active' },
      { title: 'Attendance variance', subtitle: 'Late punches and regularization requests summarized', status: 'Watch' },
    ],
    secondaryItems: [
      { title: 'Generate weekly brief', subtitle: 'Compile AI overview and management review data' },
      { title: 'Escalate risk list', subtitle: 'Notify owners of overdue operational items' },
    ],
    actions: ['Run AI Summary', 'Open Review', 'Export Snapshot'],
  },
  'attendance-punch-station': {
    layout: 'workday',
    eyebrow: 'ATTENDANCE',
    title: 'Attendance Punch Station',
    description: 'Geo-aware punching, daily attendance status, edit history, and regularization workflow.',
    icon: 'fingerprint',
    aiPrompt: 'Ask which teams are late, remote, or need attendance regularization today.',
    aiSummary: 'Attendance data is connected to today status, personal stats, policy usage, and admin attendance review APIs.',
    endpoints: ['/attendance/today', '/attendance/my/stats', '/attendance/my/policy-usage', '/attendance'],
    metrics: [
      { label: 'Today Status', value: 'Live', meta: 'Punch API ready', tone: 'tertiary', icon: 'schedule' },
      { label: 'Regularize', value: 'Open', meta: 'Manager review', tone: 'primary', icon: 'edit_calendar' },
      { label: 'Policy Use', value: 'Tracked', meta: 'Backend synced', icon: 'policy' },
      { label: 'Face Proxy', value: 'Ready', meta: 'Secure route', icon: 'face' },
    ],
    primaryItems: [
      { title: 'Punch in from verified zone', subtitle: 'Location and optional face flow available', status: 'Ready' },
      { title: 'Review missing punch', subtitle: 'Submit regularization with notes', status: 'Pending' },
      { title: 'Manager time edit', subtitle: 'Admin edits preserve history', status: 'Audited' },
    ],
    secondaryItems: [
      { title: 'Late arrival cluster', subtitle: 'Review employees with repeated variance' },
      { title: 'Policy usage trend', subtitle: 'Compare grace and work-from-home usage' },
    ],
    actions: ['Punch In', 'Punch Out', 'Regularize'],
  },
  'employee-directory': {
    layout: 'directory',
    eyebrow: 'PEOPLE',
    title: 'Employee Directory',
    description: 'Searchable employee records, departments, onboarding, colleagues, and document review.',
    icon: 'badge',
    aiPrompt: 'Ask for team composition, onboarding gaps, department capacity, or missing employee documents.',
    aiSummary: 'The directory pulls from employees, departments, colleagues, and review queues for a complete people view.',
    endpoints: ['/employees', '/employees/departments', '/employees/documents/review', '/employees/colleagues'],
    metrics: [
      { label: 'Employees', value: 'Synced', meta: 'Directory API', tone: 'tertiary', icon: 'groups' },
      { label: 'Departments', value: 'Mapped', meta: 'Org view', icon: 'account_tree' },
      { label: 'Documents', value: 'Review', meta: 'Compliance queue', tone: 'primary', icon: 'folder_shared' },
      { label: 'Onboarding', value: 'Active', meta: 'Lifecycle ready', icon: 'person_add' },
    ],
    primaryItems: [
      { title: 'New hire onboarding packet', subtitle: 'Bank details and documents pending', status: 'Action' },
      { title: 'Engineering department', subtitle: 'Capacity and reporting lines available', status: 'Active' },
      { title: 'Document review queue', subtitle: 'Identity and employment proofs ready for HR', status: 'Review' },
    ],
    secondaryItems: [
      { title: 'Create employee', subtitle: 'Add a new employee profile' },
      { title: 'Seed leave balances', subtitle: 'Prepare balances after onboarding' },
    ],
    actions: ['Add Employee', 'Review Docs', 'Departments'],
  },
  'employee-my-workday': {
    layout: 'workday',
    eyebrow: 'WORKDAY',
    title: 'Employee My Workday',
    description: 'Personal punch status, schedule, leave balance, payslip snapshot, notifications, and tasks.',
    icon: 'work_history',
    aiPrompt: 'Ask what needs your attention today across attendance, leave, salary, and assigned tasks.',
    aiSummary: 'My Workday stitches employee, attendance, calendar, salary, notifications, and corporate task APIs into one daily cockpit.',
    endpoints: ['/employees/me', '/attendance/today', '/leaves/balance', '/salary/slips/my', '/notifications', '/corporate/tasks/my'],
    metrics: [
      { label: 'Punch', value: 'Today', meta: 'Geo verified', tone: 'tertiary', icon: 'fingerprint' },
      { label: 'Leave', value: 'Balance', meta: 'Live entitlement', icon: 'event_available' },
      { label: 'Payslip', value: 'Latest', meta: 'Salary module', tone: 'primary', icon: 'payments' },
      { label: 'Inbox', value: 'AI Sorted', meta: 'Tasks and alerts', icon: 'notifications' },
    ],
    primaryItems: [
      { title: 'Timesheet approval required', subtitle: 'Review and submit your weekly work update', status: 'Priority' },
      { title: 'Townhall meeting updated', subtitle: 'Calendar reflects the latest company schedule', status: 'Info' },
      { title: 'Latest payslip available', subtitle: 'Download or review transfer status', status: 'Ready' },
    ],
    secondaryItems: [
      { title: 'Quick leave apply', subtitle: 'Start a leave request from current balance' },
      { title: 'Submit work update', subtitle: 'Send daily or weekly work summary' },
    ],
    actions: ['Punch In', 'Apply Leave', 'View Payslip'],
  },
  'leave-center': {
    layout: 'board',
    eyebrow: 'LEAVES',
    title: 'Leave Center',
    description: 'Leave application, balance visibility, manager approval, and policy-aware leave decisions.',
    icon: 'event_available',
    aiPrompt: 'Ask who is out, who overlaps on critical projects, or which leave requests need escalation.',
    aiSummary: 'Leave Center uses personal leave, balance, and approval APIs to keep employees and managers aligned.',
    endpoints: ['/leaves/my', '/leaves/balance', '/leaves'],
    metrics: [
      { label: 'Balance', value: 'Live', meta: 'Employee view', tone: 'tertiary', icon: 'calendar_month' },
      { label: 'Requests', value: 'Open', meta: 'Approval queue', tone: 'primary', icon: 'approval' },
      { label: 'Overlap Risk', value: 'AI', meta: 'Coverage signal', icon: 'group_off' },
      { label: 'Policy', value: 'Ready', meta: 'Rules enforced', icon: 'gavel' },
    ],
    primaryItems: [
      { title: 'Extended leave request', subtitle: 'Manager approval required', status: 'Pending' },
      { title: 'Sick leave balance', subtitle: 'Employee entitlement available', status: 'Active' },
      { title: 'Team coverage alert', subtitle: 'Multiple absences in same delivery pod', status: 'Risk' },
    ],
    secondaryItems: [
      { title: 'Approve leave', subtitle: 'Review pending team requests' },
      { title: 'Apply leave', subtitle: 'Submit dates and reason' },
    ],
    actions: ['Apply', 'Approve', 'View Balance'],
  },
  'expense-tracker': {
    layout: 'finance',
    eyebrow: 'FINANCE',
    title: 'Expense Tracker',
    description: 'Expense submission, L1 approval, finance approval, and paid status tracking.',
    icon: 'receipt_long',
    aiPrompt: 'Ask for high-value claims, delayed reimbursements, or policy exceptions.',
    aiSummary: 'Expense Tracker is wired to personal expenses, admin queues, approval stages, and mark-paid workflow.',
    endpoints: ['/expenses/my', '/expenses'],
    metrics: [
      { label: 'Claims', value: 'Live', meta: 'Employee + admin', tone: 'tertiary', icon: 'request_quote' },
      { label: 'L1 Queue', value: 'Open', meta: 'Manager approval', tone: 'primary', icon: 'fact_check' },
      { label: 'Finance', value: 'Review', meta: 'Payment control', icon: 'account_balance' },
      { label: 'Exceptions', value: 'AI', meta: 'Policy hints', tone: 'error', icon: 'warning' },
    ],
    primaryItems: [
      { title: 'Expense report: client visit', subtitle: 'Receipts and amount waiting for review', status: 'L1' },
      { title: 'Finance payment batch', subtitle: 'Approved claims ready to mark paid', status: 'Finance' },
      { title: 'Policy exception detected', subtitle: 'AI flagged an unusually high travel claim', status: 'Risk' },
    ],
    secondaryItems: [
      { title: 'Submit expense', subtitle: 'Create claim with category and receipt' },
      { title: 'Mark paid', subtitle: 'Close finance-approved reimbursements' },
    ],
    actions: ['Create Claim', 'Approve L1', 'Mark Paid'],
  },
  'salary-payslips': {
    layout: 'finance',
    eyebrow: 'PAYROLL',
    title: 'Salary Payslips',
    description: 'Salary structures, slip generation, approvals, transfers, rejection, and employee PDF access.',
    icon: 'payments',
    aiPrompt: 'Ask for payroll readiness, pending approvals, or transfer risk before payout.',
    aiSummary: 'Payslips are connected to salary structures, generated slips, approval and transfer routes, and employee PDF downloads.',
    endpoints: ['/salary/structures', '/salary/slips', '/salary/slips/my'],
    metrics: [
      { label: 'Structures', value: 'Ready', meta: 'Employee linked', tone: 'tertiary', icon: 'table_chart' },
      { label: 'Generated', value: 'Batch', meta: 'Payroll run', tone: 'primary', icon: 'play_circle' },
      { label: 'Approvals', value: 'Open', meta: 'Admin review', icon: 'approval' },
      { label: 'Transfers', value: 'Track', meta: 'Paid status', icon: 'send_money' },
    ],
    primaryItems: [
      { title: 'Monthly payroll batch', subtitle: 'Generate slips for the selected period', status: 'Ready' },
      { title: 'Payslip approval', subtitle: 'Review gross, deductions, and net pay', status: 'Pending' },
      { title: 'Employee PDF download', subtitle: 'Published slips are accessible to employees', status: 'Live' },
    ],
    secondaryItems: [
      { title: 'Generate slips', subtitle: 'Run payroll for active employees' },
      { title: 'Transfer salary', subtitle: 'Mark approved slips as transferred' },
    ],
    actions: ['Generate', 'Approve', 'Download PDF'],
  },
  'client-companies-overview': {
    layout: 'directory',
    eyebrow: 'CLIENTS',
    title: 'Client Companies Overview',
    description: 'Portfolio view for client companies, visits, communications, invoices, documents, and alert checks.',
    icon: 'domain',
    aiPrompt: 'Ask which clients are at risk, overdue, quiet, or ready for executive outreach.',
    aiSummary: 'Client data is connected to company records, invoices, expiring documents, and follow-up tasks for portfolio-level visibility.',
    endpoints: ['/client-companies', '/invoices', '/company-documents/expiring', '/follow-up-tasks'],
    metrics: [
      { label: 'Companies', value: 'Live', meta: 'CRM synced', tone: 'tertiary', icon: 'business' },
      { label: 'Invoices', value: 'MTD', meta: 'Payment status', tone: 'primary', icon: 'receipt' },
      { label: 'Documents', value: 'Expiring', meta: 'Compliance watch', tone: 'error', icon: 'contract' },
      { label: 'Follow-ups', value: 'AI', meta: 'Next action', icon: 'notification_important' },
    ],
    primaryItems: [
      { title: 'Live client portfolio', subtitle: 'Companies come from current EMS client records only', status: 'Live' },
      { title: 'Open follow-ups', subtitle: 'Client tasks are generated from real assignments and alerts', status: 'Review' },
      { title: 'Visit and communication gaps', subtitle: 'Risk is based on recorded visits, calls, and updates', status: 'Action' },
    ],
    secondaryItems: [
      { title: 'Run alert check', subtitle: 'Refresh client health signals' },
      { title: 'Create company', subtitle: 'Add a client with contacts and compliance data' },
    ],
    actions: ['Add Client', 'Run Alerts', 'View Invoices'],
  },
  'client-detail-gap-analysis': {
    layout: 'timeline',
    eyebrow: 'CLIENT INTEL',
    title: 'Client Detail Gap Analysis',
    description: 'Client-level gaps across documents, communications, visits, timelines, and AI summaries.',
    icon: 'rule_settings',
    aiPrompt: 'Ask what is missing for a specific client before renewal, audit, or delivery review.',
    aiSummary: 'Gap analysis is backed by client timeline, documents, communication logs, AI summaries, and follow-up tasks.',
    endpoints: ['/client-companies', '/company-documents/expiring', '/follow-up-tasks'],
    metrics: [
      { label: 'Gaps', value: 'Detected', meta: 'AI summary', tone: 'error', icon: 'report' },
      { label: 'Timeline', value: 'Ready', meta: 'Client events', icon: 'timeline' },
      { label: 'Docs', value: 'Tracked', meta: 'Expiry checks', tone: 'primary', icon: 'folder' },
      { label: 'Visits', value: 'Logged', meta: 'Field notes', tone: 'tertiary', icon: 'location_on' },
    ],
    primaryItems: [
      { title: 'Live gap signals', subtitle: 'Gaps are calculated from company activity, alerts, and follow-ups', status: 'Gap' },
      { title: 'AI next action', subtitle: 'Generate a recommendation from the selected company record', status: 'Ready' },
      { title: 'Assignable actions', subtitle: 'Create real follow-up tasks for current employees', status: 'Action' },
    ],
    secondaryItems: [
      { title: 'Generate AI summary', subtitle: 'Summarize client health and missing items' },
      { title: 'Add visit note', subtitle: 'Capture outcome from client interaction' },
    ],
    actions: ['AI Summary', 'Add Visit', 'Open Timeline'],
  },
  'calendar-meeting-notes': {
    layout: 'timeline',
    eyebrow: 'CALENDAR',
    title: 'Calendar Meeting Notes',
    description: 'Company events, upcoming schedules, audit countdowns, regulatory dates, and reviewed meeting notes.',
    icon: 'calendar_month',
    aiPrompt: 'Ask what meetings, audit deadlines, or regulatory dates need preparation this week.',
    aiSummary: 'Calendar and meeting notes combine upcoming events, audit countdowns, regulatory seeds, and reviewable meeting notes.',
    endpoints: ['/company-calendar/upcoming', '/company-calendar/audit-countdowns', '/company-calendar/regulatory', '/meeting-notes'],
    metrics: [
      { label: 'Upcoming', value: 'Events', meta: 'Calendar API', tone: 'tertiary', icon: 'event' },
      { label: 'Audit', value: 'Countdowns', meta: 'Deadline watch', tone: 'error', icon: 'timer' },
      { label: 'Regulatory', value: 'Seeded', meta: 'Compliance dates', icon: 'policy' },
      { label: 'Notes', value: 'Review', meta: 'Management ready', tone: 'primary', icon: 'edit_note' },
    ],
    primaryItems: [
      { title: 'Executive sync notes', subtitle: 'Meeting review pending', status: 'Review' },
      { title: 'Audit countdown', subtitle: 'Prepare evidence before due date', status: 'Urgent' },
      { title: 'Regulatory calendar', subtitle: 'Upcoming statutory date available', status: 'Tracked' },
    ],
    secondaryItems: [
      { title: 'Create event', subtitle: 'Add a company calendar item' },
      { title: 'Review notes', subtitle: 'Approve or comment on meeting notes' },
    ],
    actions: ['Add Event', 'Add Note', 'Seed Regulatory'],
  },
  'messaging-chat-hub': {
    layout: 'chat',
    eyebrow: 'MESSAGING',
    title: 'Messaging Chat Hub',
    description: 'Direct channels, group channels, messages, read states, and corporate chat rooms.',
    icon: 'forum',
    aiPrompt: 'Ask for unresolved conversations, unread channels, or team communication gaps.',
    aiSummary: 'Chat Hub connects direct and group chat APIs with corporate channel APIs for operational communication.',
    endpoints: ['/chat/channels', '/corporate/chat/channels', '/notifications/unread-count'],
    metrics: [
      { label: 'Channels', value: 'Live', meta: 'Direct + group', tone: 'tertiary', icon: 'forum' },
      { label: 'Unread', value: 'Count', meta: 'Notifications', tone: 'primary', icon: 'mark_chat_unread' },
      { label: 'Corporate', value: 'Rooms', meta: 'Company channels', icon: 'groups' },
      { label: 'Read State', value: 'Synced', meta: 'Per channel', icon: 'done_all' },
    ],
    primaryItems: [
      { title: 'Management channel', subtitle: 'Review latest operational thread', status: 'Unread' },
      { title: 'Direct conversation', subtitle: 'Employee follow-up waiting', status: 'Open' },
      { title: 'Corporate announcement', subtitle: 'Broadcast channel available', status: 'Active' },
    ],
    secondaryItems: [
      { title: 'Start direct chat', subtitle: 'Create a one-to-one channel' },
      { title: 'Create group', subtitle: 'Open a project or department room' },
    ],
    actions: ['New Direct', 'New Group', 'Mark Read'],
  },
  'management-review-hub': {
    layout: 'board',
    eyebrow: 'MANAGEMENT',
    title: 'Management Review Hub',
    description: 'Weekly review, AI recommendations, employee performance, and export-ready management reports.',
    icon: 'rate_review',
    aiPrompt: 'Ask what needs leadership attention across employees, approvals, finance, and client risk.',
    aiSummary: 'Management Review is backed by weekly review, AI recommendation, performance, PDF, and Excel export endpoints.',
    endpoints: ['/management-review/weekly', '/management-review/ai-recommendations', '/management-review/employee-performance'],
    metrics: [
      { label: 'Weekly', value: 'Review', meta: 'Live report', tone: 'tertiary', icon: 'summarize' },
      { label: 'AI Recs', value: 'Ready', meta: 'Recommended actions', tone: 'primary', icon: 'auto_awesome' },
      { label: 'Performance', value: '30d', meta: 'Employee signals', icon: 'monitoring' },
      { label: 'Exports', value: 'PDF/XLSX', meta: 'Board ready', icon: 'download' },
    ],
    primaryItems: [
      { title: 'Live weekly review', subtitle: 'Attendance, leaves, expenses, clients, and updates are pulled from EMS', status: 'Live' },
      { title: 'AI recommendation', subtitle: 'Prioritize pending approvals and high-risk client work', status: 'Action' },
      { title: 'Management pack', subtitle: 'Export current company status from live data', status: 'Ready' },
    ],
    secondaryItems: [
      { title: 'Export PDF', subtitle: 'Download management review deck' },
      { title: 'Export Excel', subtitle: 'Download company status workbook' },
    ],
    actions: ['Export PDF', 'Export Excel', 'Refresh AI'],
  },
  'audit-compliance-log': {
    layout: 'timeline',
    eyebrow: 'AUDIT',
    title: 'Audit Compliance Log',
    description: 'Audit logs, audit readiness projects, evidence gaps, regulatory dates, and compliance tasks.',
    icon: 'verified_user',
    aiPrompt: 'Ask what evidence is missing, what changed recently, or what audit deadline is closest.',
    aiSummary: 'Audit views combine system audit logs, readiness checklists, document expiry, and regulatory countdowns.',
    endpoints: ['/audit-logs', '/company-documents/expiring', '/company-calendar/audit-countdowns', '/company-calendar/regulatory'],
    metrics: [
      { label: 'Logs', value: 'Traceable', meta: 'Audit API', tone: 'tertiary', icon: 'history' },
      { label: 'Evidence', value: 'Gaps', meta: 'Readiness', tone: 'error', icon: 'fact_check' },
      { label: 'Docs', value: 'Expiring', meta: 'Compliance', tone: 'primary', icon: 'folder_delete' },
      { label: 'Regulatory', value: 'Dates', meta: 'Calendar linked', icon: 'event_note' },
    ],
    primaryItems: [
      { title: 'Evidence checklist gap', subtitle: 'Seed or update project readiness items', status: 'Gap' },
      { title: 'Document expiry alert', subtitle: 'Company document needs renewal', status: 'Risk' },
      { title: 'Recent admin change', subtitle: 'Audit log captured sensitive action', status: 'Logged' },
    ],
    secondaryItems: [
      { title: 'Seed readiness', subtitle: 'Create standard audit checklist' },
      { title: 'Export evidence', subtitle: 'Generate PDF package' },
    ],
    actions: ['Open Logs', 'Seed Checklist', 'Export PDF'],
  },
  'ai-talent-mapping': {
    layout: 'directory',
    eyebrow: 'TALENT',
    title: 'AI Talent Mapping',
    description: 'Talent, departments, colleagues, work maps, performance signals, and onboarding gaps.',
    icon: 'psychology',
    aiPrompt: 'Ask who is overloaded, who can cover a skill gap, or where onboarding is blocked.',
    aiSummary: 'Talent mapping blends employee directory data, AI work map, management performance, and work update signals.',
    endpoints: ['/employees', '/employees/departments', '/ai-overview/employee-work-map', '/management-review/employee-performance', '/work-updates'],
    metrics: [
      { label: 'Talent Map', value: 'AI', meta: 'Work graph', tone: 'primary', icon: 'psychology' },
      { label: 'Departments', value: 'Live', meta: 'Org data', tone: 'tertiary', icon: 'account_tree' },
      { label: 'Performance', value: '30d', meta: 'Review signals', icon: 'query_stats' },
      { label: 'Updates', value: 'Reviewed', meta: 'Manager flow', icon: 'task' },
    ],
    primaryItems: [
      { title: 'Employee workload map', subtitle: 'Uses current employee records and approved work updates', status: 'Insight' },
      { title: 'Onboarding and document gaps', subtitle: 'Shows only current employee setup/document status', status: 'Action' },
      { title: 'Performance trend', subtitle: 'Based on reviewed work updates and follow-up completion', status: 'Live' },
    ],
    secondaryItems: [
      { title: 'Review work map', subtitle: 'Inspect employee workload and collaboration' },
      { title: 'Review updates', subtitle: 'Approve or comment on submitted work' },
    ],
    actions: ['Open Work Map', 'Review Updates', 'Add Employee'],
  },
};

export const routeAliases: Record<string, keyof typeof stitchPages> = {
  'owner-command-center': 'nexus-operational-intelligence',
  'dashboard': 'employee-my-workday',
};
